// Code generated by "stringer -type=CC_Msg_Type -trimprefix=MSG_ -output=msg-cc_string.go"; DO NOT EDIT.

package dtap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MSG_CC_ALERTING-1]
	_ = x[MSG_CC_CALL_CONF-8]
	_ = x[MSG_CC_CALL_PROC-2]
	_ = x[MSG_CC_CONNECT-7]
	_ = x[MSG_CC_CONNECT_ACK-15]
	_ = x[MSG_CC_EMERG_SETUP-14]
	_ = x[MSG_CC_PROGRESS-3]
	_ = x[MSG_CC_ESTAB-4]
	_ = x[MSG_CC_ESTAB_CONF-6]
	_ = x[MSG_CC_RECALL-11]
	_ = x[MSG_CC_START_CC-9]
	_ = x[MSG_CC_SETUP-5]
	_ = x[MSG_CC_MODIFY-23]
	_ = x[MSG_CC_MODIFY_COMPL-31]
	_ = x[MSG_CC_MODIFY_REJECT-19]
	_ = x[MSG_CC_USER_INFO-16]
	_ = x[MSG_CC_HOLD-24]
	_ = x[MSG_CC_HOLD_ACK-25]
	_ = x[MSG_CC_HOLD_REJ-26]
	_ = x[MSG_CC_RETR-28]
	_ = x[MSG_CC_RETR_ACK-29]
	_ = x[MSG_CC_RETR_REJ-30]
	_ = x[MSG_CC_DISCONNECT-37]
	_ = x[MSG_CC_RELEASE-45]
	_ = x[MSG_CC_RELEASE_COMPL-42]
	_ = x[MSG_CC_CONG_CTRL-57]
	_ = x[MSG_CC_NOTIFY-62]
	_ = x[MSG_CC_STATUS-61]
	_ = x[MSG_CC_STATUS_ENQ-52]
	_ = x[MSG_CC_START_DTMF-53]
	_ = x[MSG_CC_STOP_DTMF-49]
	_ = x[MSG_CC_STOP_DTMF_ACK-50]
	_ = x[MSG_CC_START_DTMF_ACK-54]
	_ = x[MSG_CC_START_DTMF_REJ-55]
	_ = x[MSG_CC_FACILITY-58]
}

const _CC_Msg_Type_name = "CC_ALERTINGCC_CALL_PROCCC_PROGRESSCC_ESTABCC_SETUPCC_ESTAB_CONFCC_CONNECTCC_CALL_CONFCC_START_CCCC_RECALLCC_EMERG_SETUPCC_CONNECT_ACKCC_USER_INFOCC_MODIFY_REJECTCC_MODIFYCC_HOLDCC_HOLD_ACKCC_HOLD_REJCC_RETRCC_RETR_ACKCC_RETR_REJCC_MODIFY_COMPLCC_DISCONNECTCC_RELEASE_COMPLCC_RELEASECC_STOP_DTMFCC_STOP_DTMF_ACKCC_STATUS_ENQCC_START_DTMFCC_START_DTMF_ACKCC_START_DTMF_REJCC_CONG_CTRLCC_FACILITYCC_STATUSCC_NOTIFY"

var _CC_Msg_Type_map = map[CC_Msg_Type]string{
	1:  _CC_Msg_Type_name[0:11],
	2:  _CC_Msg_Type_name[11:23],
	3:  _CC_Msg_Type_name[23:34],
	4:  _CC_Msg_Type_name[34:42],
	5:  _CC_Msg_Type_name[42:50],
	6:  _CC_Msg_Type_name[50:63],
	7:  _CC_Msg_Type_name[63:73],
	8:  _CC_Msg_Type_name[73:85],
	9:  _CC_Msg_Type_name[85:96],
	11: _CC_Msg_Type_name[96:105],
	14: _CC_Msg_Type_name[105:119],
	15: _CC_Msg_Type_name[119:133],
	16: _CC_Msg_Type_name[133:145],
	19: _CC_Msg_Type_name[145:161],
	23: _CC_Msg_Type_name[161:170],
	24: _CC_Msg_Type_name[170:177],
	25: _CC_Msg_Type_name[177:188],
	26: _CC_Msg_Type_name[188:199],
	28: _CC_Msg_Type_name[199:206],
	29: _CC_Msg_Type_name[206:217],
	30: _CC_Msg_Type_name[217:228],
	31: _CC_Msg_Type_name[228:243],
	37: _CC_Msg_Type_name[243:256],
	42: _CC_Msg_Type_name[256:272],
	45: _CC_Msg_Type_name[272:282],
	49: _CC_Msg_Type_name[282:294],
	50: _CC_Msg_Type_name[294:310],
	52: _CC_Msg_Type_name[310:323],
	53: _CC_Msg_Type_name[323:336],
	54: _CC_Msg_Type_name[336:353],
	55: _CC_Msg_Type_name[353:370],
	57: _CC_Msg_Type_name[370:382],
	58: _CC_Msg_Type_name[382:393],
	61: _CC_Msg_Type_name[393:402],
	62: _CC_Msg_Type_name[402:411],
}

func (i CC_Msg_Type) String() string {
	if str, ok := _CC_Msg_Type_map[i]; ok {
		return str
	}
	return "CC_Msg_Type(" + strconv.FormatInt(int64(i), 10) + ")"
}
