// Code generated by "stringer -type=MM_Msg_Type -trimprefix=MSG_ -output=msg-mm_string.go"; DO NOT EDIT.

package dtap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MSG_MM_IMSI_DETACH_IND-1]
	_ = x[MSG_MM_LOC_UPD_ACCEPT-2]
	_ = x[MSG_MM_LOC_UPD_REJECT-4]
	_ = x[MSG_MM_LOC_UPD_REQUEST-8]
	_ = x[MSG_MM_AUTH_REJ-17]
	_ = x[MSG_MM_AUTH_REQ-18]
	_ = x[MSG_MM_AUTH_RESP-20]
	_ = x[MSG_MM_AUTH_FAIL-28]
	_ = x[MSG_MM_ID_REQ-24]
	_ = x[MSG_MM_ID_RESP-25]
	_ = x[MSG_MM_TMSI_REALL_CMD-26]
	_ = x[MSG_MM_TMSI_REALL_COMPL-27]
	_ = x[MSG_MM_CM_SERV_ACC-33]
	_ = x[MSG_MM_CM_SERV_REJ-34]
	_ = x[MSG_MM_CM_SERV_ABORT-35]
	_ = x[MSG_MM_CM_SERV_REQ-36]
	_ = x[MSG_MM_CM_SERV_PROMPT-37]
	_ = x[MSG_MM_CM_REEST_REQ-40]
	_ = x[MSG_MM_ABORT-41]
	_ = x[MSG_MM_NULL-48]
	_ = x[MSG_MM_STATUS-49]
	_ = x[MSG_MM_INFO-50]
}

const (
	_MM_Msg_Type_name_0 = "MM_IMSI_DETACH_INDMM_LOC_UPD_ACCEPT"
	_MM_Msg_Type_name_1 = "MM_LOC_UPD_REJECT"
	_MM_Msg_Type_name_2 = "MM_LOC_UPD_REQUEST"
	_MM_Msg_Type_name_3 = "MM_AUTH_REJMM_AUTH_REQ"
	_MM_Msg_Type_name_4 = "MM_AUTH_RESP"
	_MM_Msg_Type_name_5 = "MM_ID_REQMM_ID_RESPMM_TMSI_REALL_CMDMM_TMSI_REALL_COMPLMM_AUTH_FAIL"
	_MM_Msg_Type_name_6 = "MM_CM_SERV_ACCMM_CM_SERV_REJMM_CM_SERV_ABORTMM_CM_SERV_REQMM_CM_SERV_PROMPT"
	_MM_Msg_Type_name_7 = "MM_CM_REEST_REQMM_ABORT"
	_MM_Msg_Type_name_8 = "MM_NULLMM_STATUSMM_INFO"
)

var (
	_MM_Msg_Type_index_0 = [...]uint8{0, 18, 35}
	_MM_Msg_Type_index_3 = [...]uint8{0, 11, 22}
	_MM_Msg_Type_index_5 = [...]uint8{0, 9, 19, 36, 55, 67}
	_MM_Msg_Type_index_6 = [...]uint8{0, 14, 28, 44, 58, 75}
	_MM_Msg_Type_index_7 = [...]uint8{0, 15, 23}
	_MM_Msg_Type_index_8 = [...]uint8{0, 7, 16, 23}
)

func (i MM_Msg_Type) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MM_Msg_Type_name_0[_MM_Msg_Type_index_0[i]:_MM_Msg_Type_index_0[i+1]]
	case i == 4:
		return _MM_Msg_Type_name_1
	case i == 8:
		return _MM_Msg_Type_name_2
	case 17 <= i && i <= 18:
		i -= 17
		return _MM_Msg_Type_name_3[_MM_Msg_Type_index_3[i]:_MM_Msg_Type_index_3[i+1]]
	case i == 20:
		return _MM_Msg_Type_name_4
	case 24 <= i && i <= 28:
		i -= 24
		return _MM_Msg_Type_name_5[_MM_Msg_Type_index_5[i]:_MM_Msg_Type_index_5[i+1]]
	case 33 <= i && i <= 37:
		i -= 33
		return _MM_Msg_Type_name_6[_MM_Msg_Type_index_6[i]:_MM_Msg_Type_index_6[i+1]]
	case 40 <= i && i <= 41:
		i -= 40
		return _MM_Msg_Type_name_7[_MM_Msg_Type_index_7[i]:_MM_Msg_Type_index_7[i+1]]
	case 48 <= i && i <= 50:
		i -= 48
		return _MM_Msg_Type_name_8[_MM_Msg_Type_index_8[i]:_MM_Msg_Type_index_8[i+1]]
	default:
		return "MM_Msg_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
