// Code generated by "stringer -type=PD_Type -trimprefix=PD_ -output=pd_string.go"; DO NOT EDIT.

package dtap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PD_GROUP_CC-0]
	_ = x[PD_BCAST_CC-1]
	_ = x[PD_EPS_SMM-2]
	_ = x[PD_CC-3]
	_ = x[PD_GTTP-4]
	_ = x[PD_MM-5]
	_ = x[PD_RR-6]
	_ = x[PD_EPS_MMM-7]
	_ = x[PD_GPRS_MMM-8]
	_ = x[PD_SMS-9]
	_ = x[PD_GPRS_SMM-10]
	_ = x[PD_SS_NCL-11]
	_ = x[PD_LOC-12]
	_ = x[PD_EXTEND-14]
	_ = x[PD_TEST-15]
}

const (
	_PD_Type_name_0 = "GROUP_CCBCAST_CCEPS_SMMCCGTTPMMRREPS_MMMGPRS_MMMSMSGPRS_SMMSS_NCLLOC"
	_PD_Type_name_1 = "EXTENDTEST"
)

var (
	_PD_Type_index_0 = [...]uint8{0, 8, 16, 23, 25, 29, 31, 33, 40, 48, 51, 59, 65, 68}
	_PD_Type_index_1 = [...]uint8{0, 6, 10}
)

func (i PD_Type) String() string {
	switch {
	case i <= 12:
		return _PD_Type_name_0[_PD_Type_index_0[i]:_PD_Type_index_0[i+1]]
	case 14 <= i && i <= 15:
		i -= 14
		return _PD_Type_name_1[_PD_Type_index_1[i]:_PD_Type_index_1[i+1]]
	default:
		return "PD_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
