// Code generated by "stringer -type=ChType --output=channel_type_string.go"; DO NOT EDIT.

package bssmap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CT_Invalid-0]
	_ = x[CT_TCH_F-1]
	_ = x[CT_TCH_H-2]
	_ = x[CT_TCH_F_H-3]
	_ = x[CT_SDCCH-4]
	_ = x[CT_SDCCH_TCH_F-5]
	_ = x[CT_SDCCH_TCH_H-6]
	_ = x[CT_SDCCH_TCH_F_H-7]
}

const _ChType_name = "CT_InvalidCT_TCH_FCT_TCH_HCT_TCH_F_HCT_SDCCHCT_SDCCH_TCH_FCT_SDCCH_TCH_HCT_SDCCH_TCH_F_H"

var _ChType_index = [...]uint8{0, 10, 18, 26, 36, 44, 58, 72, 88}

func (i ChType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChType_index)-1 {
		return "ChType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChType_name[_ChType_index[idx]:_ChType_index[idx+1]]
}
