// Code generated by "stringer -type=BSSMAP_SDI --output=channel_sdi_string.go"; DO NOT EDIT.

package bssmap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SDISpeech-1]
	_ = x[SDIData-2]
	_ = x[SDISignaling-3]
	_ = x[SDISpeechCTMTelephony-4]
}

const _BSSMAP_SDI_name = "SDISpeechSDIDataSDISignalingSDISpeechCTMTelephony"

var _BSSMAP_SDI_index = [...]uint8{0, 9, 16, 28, 49}

func (i BSSMAP_SDI) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_BSSMAP_SDI_index)-1 {
		return "BSSMAP_SDI(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BSSMAP_SDI_name[_BSSMAP_SDI_index[idx]:_BSSMAP_SDI_index[idx+1]]
}
