// Code generated by "stringer -type=BSSMAPChannelMode --output=channel_mode_string.go"; DO NOT EDIT.

package bssmap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CM_NO_MODE-0]
	_ = x[CM_SPEECH-9]
	_ = x[CM_DATA_14_5_14_5-14]
	_ = x[CM_DATA_12_0_12_0-11]
	_ = x[CM_DATA_6_0_6_0-12]
	_ = x[CM_DATA_3_6_3_6-13]
	_ = x[CM_SIGNALLING-8]
	_ = x[CM_DATA_29_0_29_0-1]
	_ = x[CM_DATA_32_0_32_0-2]
	_ = x[CM_DATA_43_5_43_5-3]
	_ = x[CM_DATA_43_5_14_5-4]
	_ = x[CM_DATA_29_0_14_5-5]
	_ = x[CM_DATA_43_5_29_0-6]
	_ = x[CM_DATA_14_5_43_5-7]
	_ = x[CM_DATA_14_5_29_0-10]
	_ = x[CM_DATA_29_0_43_5-15]
}

const _BSSMAPChannelMode_name = "CM_NO_MODECM_DATA_29_0_29_0CM_DATA_32_0_32_0CM_DATA_43_5_43_5CM_DATA_43_5_14_5CM_DATA_29_0_14_5CM_DATA_43_5_29_0CM_DATA_14_5_43_5CM_SIGNALLINGCM_SPEECHCM_DATA_14_5_29_0CM_DATA_12_0_12_0CM_DATA_6_0_6_0CM_DATA_3_6_3_6CM_DATA_14_5_14_5CM_DATA_29_0_43_5"

var _BSSMAPChannelMode_index = [...]uint8{0, 10, 27, 44, 61, 78, 95, 112, 129, 142, 151, 168, 185, 200, 215, 232, 249}

func (i BSSMAPChannelMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BSSMAPChannelMode_index)-1 {
		return "BSSMAPChannelMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BSSMAPChannelMode_name[_BSSMAPChannelMode_index[idx]:_BSSMAPChannelMode_index[idx+1]]
}
