// Code generated by "stringer -type=BSSMAPChosenChannel --output=chosen_channel_string.go"; DO NOT EDIT.

package bssmap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CHANNEL_NONE-0]
	_ = x[CHANNEL_SDCCH-1]
	_ = x[CHANNEL_TCH_F-8]
	_ = x[CHANNEL_TCH_H-9]
	_ = x[CHANNEL_2_TCH_F-10]
	_ = x[CHANNEL_3_TCH_F-11]
	_ = x[CHANNEL_4_TCH_F-12]
	_ = x[CHANNEL_5_TCH_F-13]
	_ = x[CHANNEL_6_TCH_F-14]
	_ = x[CHANNEL_7_TCH_F-15]
	_ = x[CHANNEL_8_TCH_F-4]
}

const (
	_BSSMAPChosenChannel_name_0 = "CHANNEL_NONECHANNEL_SDCCH"
	_BSSMAPChosenChannel_name_1 = "CHANNEL_8_TCH_F"
	_BSSMAPChosenChannel_name_2 = "CHANNEL_TCH_FCHANNEL_TCH_HCHANNEL_2_TCH_FCHANNEL_3_TCH_FCHANNEL_4_TCH_FCHANNEL_5_TCH_FCHANNEL_6_TCH_FCHANNEL_7_TCH_F"
)

var (
	_BSSMAPChosenChannel_index_0 = [...]uint8{0, 12, 25}
	_BSSMAPChosenChannel_index_2 = [...]uint8{0, 13, 26, 41, 56, 71, 86, 101, 116}
)

func (i BSSMAPChosenChannel) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _BSSMAPChosenChannel_name_0[_BSSMAPChosenChannel_index_0[i]:_BSSMAPChosenChannel_index_0[i+1]]
	case i == 4:
		return _BSSMAPChosenChannel_name_1
	case 8 <= i && i <= 15:
		i -= 8
		return _BSSMAPChosenChannel_name_2[_BSSMAPChosenChannel_index_2[i]:_BSSMAPChosenChannel_index_2[i+1]]
	default:
		return "BSSMAPChosenChannel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
