package bssmap

import (
	"fmt"
)

type BSSMAP_MsgType byte

const (
	MSG_RESERVED_0 BSSMAP_MsgType = 0

	/* ASSIGNMENT MESSAGES */
	MSG_ASSIGNMENT_RQST    BSSMAP_MsgType = 1
	MSG_ASSIGNMENT_CMPL    BSSMAP_MsgType = 2
	MSG_ASSIGNMENT_FAILURE BSSMAP_MsgType = 3
	MSG_CHAN_MOD_RQST      BSSMAP_MsgType = 8

	/*  HO MESSAGES */
	MSG_HO_RQST             BSSMAP_MsgType = 16
	MSG_HO_REQUIRED         BSSMAP_MsgType = 17
	MSG_HO_RQST_ACK         BSSMAP_MsgType = 18
	MSG_HO_CMD              BSSMAP_MsgType = 19
	MSG_HO_CMPL             BSSMAP_MsgType = 20
	MSG_HO_SUCCEEDED        BSSMAP_MsgType = 21
	MSG_HO_FAILURE          BSSMAP_MsgType = 22
	MSG_HO_PERFORMED        BSSMAP_MsgType = 23
	MSG_HO_CAND_ENQ         BSSMAP_MsgType = 24
	MSG_HO_CAND_RESP        BSSMAP_MsgType = 25
	MSG_HO_REQUIRED_REJ     BSSMAP_MsgType = 26
	MSG_HO_DETECT           BSSMAP_MsgType = 27
	MSG_INT_HO_REQUIRED     BSSMAP_MsgType = 0x70
	MSG_INT_HO_REQUIRED_REJ BSSMAP_MsgType = 0x71
	MSG_INT_HO_CMD          BSSMAP_MsgType = 0x72
	MSG_INT_HO_ENQUIRY      BSSMAP_MsgType = 0x73

	/* RELEASE MESSAGES */
	MSG_CLEAR_CMD     BSSMAP_MsgType = 32
	MSG_CLEAR_CMPL    BSSMAP_MsgType = 33
	MSG_CLEAR_RQST    BSSMAP_MsgType = 34
	MSG_RESERVED_1    BSSMAP_MsgType = 35
	MSG_RESERVED_2    BSSMAP_MsgType = 36
	MSG_SAPI_N_REJECT BSSMAP_MsgType = 37
	MSG_CONFUSION     BSSMAP_MsgType = 38

	/* OTHER CONNECTION RELATED MESSAGES */
	MSG_SUSPEND                 BSSMAP_MsgType = 40
	MSG_RESUME                  BSSMAP_MsgType = 41
	MSG_CONNECTION_ORIENTED_INF BSSMAP_MsgType = 42
	MSG_PERFORM_LOCATION_RQST   BSSMAP_MsgType = 43
	MSG_LSA_INFORMATION         BSSMAP_MsgType = 44
	MSG_PERFORM_LOCATION_RESP   BSSMAP_MsgType = 45
	MSG_PERFORM_LOCATION_ABORT  BSSMAP_MsgType = 46
	MSG_COMMON_ID               BSSMAP_MsgType = 47
	MSG_REROUTE_CMD             BSSMAP_MsgType = 0x78
	MSG_REROUTE_CMPL            BSSMAP_MsgType = 0x79

	/* GENERAL MESSAGES */
	MSG_RESET              BSSMAP_MsgType = 48
	MSG_RESET_ACK          BSSMAP_MsgType = 49
	MSG_OVERLOAD           BSSMAP_MsgType = 50
	MSG_RESERVED_3         BSSMAP_MsgType = 51
	MSG_RESET_CIRCUIT      BSSMAP_MsgType = 52
	MSG_RESET_CIRCUIT_ACK  BSSMAP_MsgType = 53
	MSG_MSC_INVOKE_TRACE   BSSMAP_MsgType = 54
	MSG_BSS_INVOKE_TRACE   BSSMAP_MsgType = 55
	MSG_CONNECTIONLESS_INF BSSMAP_MsgType = 58
	MSG_RESET_IP_RSRC      BSSMAP_MsgType = 0x3d
	MSG_RESET_IP_RSRC_ACK  BSSMAP_MsgType = 0x3e

	/* TERRESTRIAL RESOURCE MESSAGES */
	MSG_BLK                BSSMAP_MsgType = 64
	MSG_BLK_ACK            BSSMAP_MsgType = 65
	MSG_UNBLK              BSSMAP_MsgType = 66
	MSG_UNBLK_ACK          BSSMAP_MsgType = 67
	MSG_CG_BLK             BSSMAP_MsgType = 68
	MSG_CG_BLK_ACK         BSSMAP_MsgType = 69
	MSG_CG_UNBLK           BSSMAP_MsgType = 70
	MSG_CG_UNBLK_ACK       BSSMAP_MsgType = 71
	MSG_UNEQUIPPED_CIRCUIT BSSMAP_MsgType = 72
	MSG_CHANGE_CIRCUIT     BSSMAP_MsgType = 78
	MSG_CHANGE_CIRCUIT_ACK BSSMAP_MsgType = 79

	/* RADIO RESOURCE MESSAGES */
	MSG_RESOURCE_RQST       BSSMAP_MsgType = 80
	MSG_RESOURCE_INDICATION BSSMAP_MsgType = 81
	MSG_PAGING              BSSMAP_MsgType = 82
	MSG_CIPHER_MODE_CMD     BSSMAP_MsgType = 83
	MSG_CLASSMARK_UPDATE    BSSMAP_MsgType = 84
	MSG_CIPHER_MODE_CMPL    BSSMAP_MsgType = 85
	MSG_QUEUING_INDICATION  BSSMAP_MsgType = 86
	MSG_CMPL_LAYER_3        BSSMAP_MsgType = 87
	MSG_CLASSMARK_RQST      BSSMAP_MsgType = 88
	MSG_CIPHER_MODE_REJECT  BSSMAP_MsgType = 89
	MSG_LOAD_INDICATION     BSSMAP_MsgType = 90

	/* VGCS/VBS */
	MSG_VGCS_VBS_SETUP              BSSMAP_MsgType = 4
	MSG_VGCS_VBS_SETUP_ACK          BSSMAP_MsgType = 5
	MSG_VGCS_VBS_SETUP_REFUSE       BSSMAP_MsgType = 6
	MSG_VGCS_VBS_ASSIGNMENT_RQST    BSSMAP_MsgType = 7
	MSG_VGCS_VBS_ASSIGNMENT_RESULT  BSSMAP_MsgType = 28
	MSG_VGCS_VBS_ASSIGNMENT_FAILURE BSSMAP_MsgType = 29
	MSG_VGCS_VBS_QUEUING_INDICATION BSSMAP_MsgType = 30
	MSG_UPLINK_RQST                 BSSMAP_MsgType = 31
	MSG_UPLINK_RQST_ACK             BSSMAP_MsgType = 39
	MSG_VGCS_VBS_ASSIGNMENT_STATUS  BSSMAP_MsgType = 59
	MSG_VGCS_VBS_AREA_CELL_INFO     BSSMAP_MsgType = 60
	MSG_UPLINK_RQST_CONFIRMATION    BSSMAP_MsgType = 73
	MSG_UPLINK_RELEASE_INDICATION   BSSMAP_MsgType = 74
	MSG_UPLINK_REJECT_CMD           BSSMAP_MsgType = 75
	MSG_UPLINK_RELEASE_CMD          BSSMAP_MsgType = 76
	MSG_UPLINK_SEIZED_CMD           BSSMAP_MsgType = 77
	MSG_VGCS_ADDL_INFO              BSSMAP_MsgType = 0x60
	MSG_VGCS_SMS                    BSSMAP_MsgType = 0x61
	MSG_NOTIFICATION_DATA           BSSMAP_MsgType = 0x62
	MSG_UPLINK_APP_DATA             BSSMAP_MsgType = 0x63

	/* LOCAL SWITCHING */
	MSG_LCLS_CONNECT_CTRL     BSSMAP_MsgType = 0x74
	MSG_LCLS_CONNECT_CTRL_ACK BSSMAP_MsgType = 0x75
	MSG_LCLS_NOTIFICATION     BSSMAP_MsgType = 0x76
)

func (m BSSMAP_MsgType) String() string {
	switch m {
	case MSG_ASSIGNMENT_RQST:
		return "AssReq"
	case MSG_ASSIGNMENT_CMPL:
		return "AssCmpt"
	default:
		return fmt.Sprintf("Bssmap0x%02X", int(m))
	}
}
