// Code generated by "stringer -type=MT -trimprefix=MT_ -output=mt_string.go"; DO NOT EDIT.

package abisrsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MT_DATA_REQ-1]
	_ = x[MT_DATA_IND-2]
	_ = x[MT_ERROR_IND-3]
	_ = x[MT_EST_REQ-4]
	_ = x[MT_EST_CONF-5]
	_ = x[MT_EST_IND-6]
	_ = x[MT_REL_REQ-7]
	_ = x[MT_REL_CONF-8]
	_ = x[MT_REL_IND-9]
	_ = x[MT_UNIT_DATA_REQ-10]
	_ = x[MT_UNIT_DATA_IND-11]
	_ = x[MT_SUSP_REQ-12]
	_ = x[MT_SUSP_CONF-13]
	_ = x[MT_RES_REQ-14]
	_ = x[MT_RECON_REQ-15]
	_ = x[MT_BCCH_INFO-17]
	_ = x[MT_CCCH_LOAD_IND-18]
	_ = x[MT_CHAN_RQD-19]
	_ = x[MT_DELETE_IND-20]
	_ = x[MT_PAGING_CMD-21]
	_ = x[MT_IMMEDIATE_ASSIGN_CMD-22]
	_ = x[MT_SMS_BC_REQ-23]
	_ = x[MT_CHAN_CONF-24]
	_ = x[MT_RF_RES_IND-25]
	_ = x[MT_SACCH_FILL-26]
	_ = x[MT_OVERLOAD-27]
	_ = x[MT_ERROR_REPORT-28]
	_ = x[MT_SMS_BC_CMD-29]
	_ = x[MT_CBCH_LOAD_IND-30]
	_ = x[MT_NOT_CMD-31]
	_ = x[MT_CHAN_ACTIV-33]
	_ = x[MT_CHAN_ACTIV_ACK-34]
	_ = x[MT_CHAN_ACTIV_NACK-35]
	_ = x[MT_CONN_FAIL-36]
	_ = x[MT_DEACTIVATE_SACCH-37]
	_ = x[MT_ENCR_CMD-38]
	_ = x[MT_HANDO_DET-39]
	_ = x[MT_MEAS_RES-40]
	_ = x[MT_MODE_MODIFY_REQ-41]
	_ = x[MT_MODE_MODIFY_ACK-42]
	_ = x[MT_MODE_MODIFY_NACK-43]
	_ = x[MT_PHY_CONTEXT_REQ-44]
	_ = x[MT_PHY_CONTEXT_CONF-45]
	_ = x[MT_RF_CHAN_REL-46]
	_ = x[MT_MS_POWER_CONTROL-47]
	_ = x[MT_BS_POWER_CONTROL-48]
	_ = x[MT_PREPROC_CONFIG-49]
	_ = x[MT_PREPROC_MEAS_RES-50]
	_ = x[MT_RF_CHAN_REL_ACK-51]
	_ = x[MT_SACCH_INFO_MODIFY-52]
	_ = x[MT_TALKER_DET-53]
	_ = x[MT_LISTENER_DET-54]
	_ = x[MT_REMOTE_CODEC_CONF_REP-55]
	_ = x[MT_RTD_REP-56]
	_ = x[MT_PRE_HANDO_NOTIF-57]
	_ = x[MT_MR_CODEC_MOD_REQ-58]
	_ = x[MT_MR_CODEC_MOD_ACK-59]
	_ = x[MT_MR_CODEC_MOD_NACK-60]
	_ = x[MT_MR_CODEC_MOD_PER-61]
	_ = x[MT_TFO_REP-62]
	_ = x[MT_TFO_MOD_REQ-63]
	_ = x[MT_LOCATION_INFO-65]
}

const (
	_MT_name_0 = "DATA_REQDATA_INDERROR_INDEST_REQEST_CONFEST_INDREL_REQREL_CONFREL_INDUNIT_DATA_REQUNIT_DATA_INDSUSP_REQSUSP_CONFRES_REQRECON_REQ"
	_MT_name_1 = "BCCH_INFOCCCH_LOAD_INDCHAN_RQDDELETE_INDPAGING_CMDIMMEDIATE_ASSIGN_CMDSMS_BC_REQCHAN_CONFRF_RES_INDSACCH_FILLOVERLOADERROR_REPORTSMS_BC_CMDCBCH_LOAD_INDNOT_CMD"
	_MT_name_2 = "CHAN_ACTIVCHAN_ACTIV_ACKCHAN_ACTIV_NACKCONN_FAILDEACTIVATE_SACCHENCR_CMDHANDO_DETMEAS_RESMODE_MODIFY_REQMODE_MODIFY_ACKMODE_MODIFY_NACKPHY_CONTEXT_REQPHY_CONTEXT_CONFRF_CHAN_RELMS_POWER_CONTROLBS_POWER_CONTROLPREPROC_CONFIGPREPROC_MEAS_RESRF_CHAN_REL_ACKSACCH_INFO_MODIFYTALKER_DETLISTENER_DETREMOTE_CODEC_CONF_REPRTD_REPPRE_HANDO_NOTIFMR_CODEC_MOD_REQMR_CODEC_MOD_ACKMR_CODEC_MOD_NACKMR_CODEC_MOD_PERTFO_REPTFO_MOD_REQ"
	_MT_name_3 = "LOCATION_INFO"
)

var (
	_MT_index_0 = [...]uint8{0, 8, 16, 25, 32, 40, 47, 54, 62, 69, 82, 95, 103, 112, 119, 128}
	_MT_index_1 = [...]uint8{0, 9, 22, 30, 40, 50, 70, 80, 89, 99, 109, 117, 129, 139, 152, 159}
	_MT_index_2 = [...]uint16{0, 10, 24, 39, 48, 64, 72, 81, 89, 104, 119, 135, 150, 166, 177, 193, 209, 223, 239, 254, 271, 281, 293, 314, 321, 336, 352, 368, 385, 401, 408, 419}
)

func (i MT) String() string {
	switch {
	case 1 <= i && i <= 15:
		i -= 1
		return _MT_name_0[_MT_index_0[i]:_MT_index_0[i+1]]
	case 17 <= i && i <= 31:
		i -= 17
		return _MT_name_1[_MT_index_1[i]:_MT_index_1[i+1]]
	case 33 <= i && i <= 63:
		i -= 33
		return _MT_name_2[_MT_index_2[i]:_MT_index_2[i+1]]
	case i == 65:
		return _MT_name_3
	default:
		return "MT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
